@baseUrl = http://localhost:3333
@userId = {{register_account.response.body.attributes.id}}

# @name register_account
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "test@example.co.uk",
  "password": "123456"
}

###

# @name confirm_account
POST {{baseUrl}}/auth/confirm
Content-Type: application/json

{
  "id": "dfcfc499-6325-494d-9739-c5af5234643a"
}

###

# @name authenticate
POST {{baseUrl}}/auth/login
Content-Type: application/json

{ 
  "email": "test@examplqwee.co.uk",
  "password": "123456"
}

###

# @name refresh_token
PATCH {{baseUrl}}/auth/token/refresh
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "123456"
}

###

# @name create_token
POST {{baseUrl}}/auth/user-token/create
Content-Type: application/json

{
  "userId": "960c60f9-b2d2-4eb6-a262-ac108a0ebfef",
  "type": "password_reset" 
}
### "type":  "account_confirmation""

###

# @name change_password
PATCH {{baseUrl}}/auth/change-password
Content-Type: application/json

{
  "userId": "960c60f9-b2d2-4eb6-a262-ac108a0ebfef",
  "tokenId": "be9fa856-d34b-4784-9d1d-0d447faf47cf",
  "password": "123456789"
}