@baseUrl = http://localhost:3333

# @name register_account
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "123456"
}

###

# @name confirm_account
POST {{baseUrl}}/auth/confirm
Content-Type: application/json

{
  "id": "f7be122e-0eee-4ed0-ba40-56aab7ed443e"
}

###

# @name authenticate
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "123456"
}
