@baseUrl = http://localhost:3333

# @name register_account
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "test@example123.com",
  "password": "123456"
}

###

# @name confirm_account
POST {{baseUrl}}/auth/confirm
Content-Type: application/json

{
  "id": "2edb41f3-331a-4da1-a7a5-8c8a4c4d9a86"
}

# ###

# # @name authenticate
# POST {{baseUrl}}/sessions
# Content-Type: application/json

# {
#   "email": "test@example.com",
#   "password": "123456"
# }
