@baseUrl = http://localhost:3333

# @name register account
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "123456"
}

# ###

# # @name authenticate
# POST {{baseUrl}}/sessions
# Content-Type: application/json

# {
#   "email": "test@example.com",
#   "password": "123456"
# }
